### ISSUE TITLE
Fix UPM install URL on README.md

### ISSUE THREAD

**Issue by sh0ou** [nuruwo8/vrchat-dark-class-generator#3]
The URL listed in [README.md](https://github.com/nuruwo8/vrchat-dark-class-generator/blob/main/README.md) is still in my repository.
`https://github.com/sh0ou/vrchat-dark-class-generator.git#feature/support-upm`

This was created for a working preview of PR #2 , so it should actually refer to your repository URL.
`https://github.com/nuruwo8/vrchat-dark-class-generator.git`

Entering this repository URL works as shown in the image.
![image](https://github.com/user-attachments/assets/555d7cf4-46fd-4fc1-b395-9eadf4c116cd)
![image](https://github.com/user-attachments/assets/5cad14fb-3eb5-459b-b872-6415c4c7952d)

**Comment by nuruwo8** [comment]
Sorry, I didn't notice. Fixed it!
